name: Unit3 Tests
on: 
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths: ["unit3/exercises/e**"]
    # branches-ignore: ["master", "main"]
jobs: 
  test:
    name: "Test exercises"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        excercise: [0,1,2]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>1.18.0'
      - uses: actions/checkout@v3
      - name: Exercise ${{ matrix.excercise }}
        run: ./unit3/exercise.test.sh ${{ matrix.excercise }}
        env:
          CGO_ENABLED: 0
        working-directory: .ci
